import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main> */}
      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}

      {/* contoh untuk scss nasting dan variables */}
      {/* <div className="container">
        <div className="main">
          <div className="main-header">
            <h1>Test Nesting SCSS</h1>
          </div>
          <div className="main-paragraf">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime iure exercitationem quas eius recusandae! Et ut dolore ipsam ea corrupti?</p>
          </div>
        </div>
      </div>

      <div className="footer">
        <div className="footer-heading">
          <h1>
            Testing
          </h1>
        </div>
        <div className="footer-developed">
          <p>
            developed by Wira Chanra
          </p>
        </div>
      </div> */}

      {/* contoh untuk mixins */}

      <div className="header">
        {/* ul>li*5>a{Link $$} contoh emet mempercepat buat ul dan li hasil dibawah */}
        <ul>
          <li><a href="">link 01</a></li>
          <li><a href="">link 02</a></li>
          <li><a href="">link 03</a></li>
          <li><a href="">link 04</a></li>
          <li><a href="">link 05</a></li>
        </ul>
      </div>

      <div className="main">
        <ul className='social-link'>
          <li><a href="" className='main1'>link 01</a></li>
          <li><a href="" className='main2'>link 02</a></li>
          <li><a href="" className='main3'>link 03</a></li>
          <li><a href="" className='main4'>link 04</a></li>
          <li><a href="" className='main5'>link 05</a></li>
          <li><a href="" className='main5'>link 06</a></li>
          <li><a href="" className='main5'>link 07</a></li>
          <li><a href="" className='main5'>link 08</a></li>
          <li><a href="" className='main5'>link 09</a></li>
        </ul>
      </div>

      {/* ini contoh untuk mixins arguments */}
      <div className="container">
        <div className="box">1</div>
        <div className="box">2</div>
        <div className="box">3</div>
      </div>

      <div className="footer">
        <ul>
          <li><a href="">link 01</a></li>
          <li><a href="">link 02</a></li>
          <li><a href="">link 03</a></li>
          <li><a href="">link 04</a></li>
          <li><a href="">link 05</a></li>
        </ul>
      </div>

    </div>
  )
}
