import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
 return (
  <div className={styles.container}>
   <Head>
    <title>Create Next App Test</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
   </Head>

   {/* contoh untuk mixins */}

   <div className="header">
    {/* ul>li*5>a{Link $$} contoh emet mempercepat buat ul dan li hasil dibawah */}
    <ul>
     <li><a href="">link 01</a></li>
     <li><a href="">link 02</a></li>
     <li><a href="">link 03</a></li>
     <li><a href="">link 04</a></li>
     <li><a href="">link 05</a></li>
     <li><a href="">link 06</a></li>
     <li><a href="">link 07</a></li>
     <li><a href="">link 08</a></li>
    </ul>
   </div>

   <div className="main">
    <ul className='social-link'>
     <li><a href="" className='main1'>link 01</a></li>
     <li><a href="" className='main2'>link 02</a></li>
     <li><a href="" className='main3'>link 03</a></li>
     <li><a href="" className='main4'>link 04</a></li>
     <li><a href="" className='main5'>link 05</a></li>
    </ul>
   </div>

   {/* ini contoh untuk mixins arguments */}
   <div className="container">
    <div className="box">1</div>
    <div className="box">2</div>
    <div className="box">3</div>
   </div>

   <div className="footer">
    <ul>
     <li><a href="">link 01</a></li>
     <li><a href="">link 02</a></li>
     <li><a href="">link 03</a></li>
     <li><a href="">link 04</a></li>
     <li><a href="">link 05</a></li>
    </ul>
   </div>

  </div>
 )
}
